### ISSUE TITLE
Testumgebung mit Test HBCI Server erstellen

### ISSUE THREAD

**Issue by kicktipp** [hbci4j/hbci4java#1]
Zurzeit laufen viele Test gegen ein echtes Testkonto. Wir sollten für diese IntegrationTests eine Umgebung starten, so dass die Tests mit einem lokalen HBCI Server kommunizieren können

**Comment by willuhn** [comment]
Ich mach das Ticket mal zu. Vor PSD2 haette man vielleicht noch den HBCI4Java-Server irgendwie reaktivieren koennen. Jetzt aber faellt mir kein Weg mehr ein, irgendwie einen eigenen lokalen HBCI-Server realistisch zu betreiben. Selbst wenn man in den irgendwie PSD2-Support reinbasteln wuerde, waere es kein wirklicher realistischer Test, weil man da nur gegen sich selbst testet. Der HBCI-Server sollte von jemandem anderes stammen.

**Comment by valb3r** [comment]
Hi @willuhn 
I'm the contributor of OpenBankingGateway (https://github.com/adorsys/open-banking-gateway).
We have actually implemented HBCI Sandbox that supports account, transaction listing payments with SCA (and it is backed by the fork your library, so many thanks for the library).

The Sandbox is located here: https://github.com/adorsys/open-banking-gateway/tree/develop/opba-protocols/sandboxes/hbci-sandbox

My proposal is, maybe you can use it in your tests and our project will benefit as there will be more testers of our HBCI-Sandbox?

**Comment by willuhn** [comment]
Thanks @valb3r for the info.
