### ISSUE TITLE
Build-Probleme ("API incompatibility")

### ISSUE THREAD

**Issue by fleather** [hbci4j/hbci4java#101]
Hi,

beim "mvn package" in master bekomme ich folgende Ausgaben:

`[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.14.0:generate (pain.001.001.03) on project hbci4j-core: Execution pain.001.001.03 of goal org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.14.0:generate: java.lang.ExceptionInInitializerError: null
`

Fehlt irgendetwas?

VG Stefan

**Comment by willuhn** [comment]
Welche Java-Version verwendest du? Mit Java 11 sollte der Fehler nicht auftreten.

**Comment by willuhn** [comment]
Verwende bitte Java 11. Da geht das.
