### ISSUE TITLE
Unterstützung für das CAMT Format

### ISSUE THREAD

**Issue by schnobbl** [hbci4j/hbci4java#15]
Hallo zusammen,

gibt es schon Planungen für die Unterstützung des CAMT Nachrichtenformats bei der Umsatzabfrage? Hier wären viele Zusatzinfos verfügbar, die beim alten MT9xx Format leider fehlen, z.B. die PaymentInfId von Sammellastschriften.

Gruss
Norbert

**Comment by willuhn** [comment]
Nein, noch nicht. Aber wenn du willst, kannst du gern einen Pull-Request dazu machen.
