### ISSUE TITLE
Source vom Server?

### ISSUE THREAD

**Issue by bennaux** [hbci4j/hbci4java#21]
Irre ich mich, oder fehlen die Sources vom Server? Kann man die irgendwo anders finden?

**Comment by willuhn** [comment]
Das ist korrekt. HBCI4Java stammt ja urspruenglich von Stefan Palme. Seine Webseite unter http://hbci4java.kapott.org/index.html ist noch erreichbar. Ab etwa 2009 habe ich die Weiterentwicklung fortgefuehrt. Den Source des Servers hat Stefan leider nie veroeffentlicht, sodass ich ihn nicht weiter pflegen konnte. Ich wollte aber zumindest den letzten Release-Stand erhalten, damit er nicht komplett verloren geht.

**Comment by bennaux** [comment]
Oh stimmt, darüber hatten wir ja schon mal gemailt...

Ich hab gerade nochmal kurz in die Dateien reingeschaut: Da ist ja eine Datei COPYING, in der allem Anschein nach die GNU GPL drinsteht. Wäre es dann nicht erlaubt, die Klassen zu disassemblieren und den entstehenden Code weiterzuentwickeln? Es sind ja sogar javadocs dabei.

**Comment by willuhn** [comment]
> Ich hab gerade nochmal kurz in die Dateien reingeschaut: Da ist ja eine
> Datei COPYING, in der allem Anschein nach die GNU GPL drinsteht.
> Wäre es dann nicht erlaubt, die Klassen zu disassemblieren und den
> entstehenden Code weiterzuentwickeln? Es sind ja sogar javadocs dabei.

Ob man selbst decompilieren darf, weiss ich nicht. Auf Nummer sicher wuerdest du gehen, wenn du Stefan hierzu einfach mal eine Mail schreibst.

**Comment by willuhn** [comment]
Ne, neuere Kontaktdaten habe ich leider auch nicht. Aber wenn die Mail nicht als unzustellbar zurueck kam, wird er sie wohl erhalten haben.

**Comment by bennaux** [comment]
...leider bislang nichts zurückgekommen. :-(

**Comment by bennaux** [comment]
Da hab ich ihn sogar gefunden!! Aber leider hab ich kein Premium und kann ihm deshalb keine Nachricht schreiben... Kannst du das eventuell?

**Comment by reikjarloekl** [comment]
Hi. [Hier](https://sourceforge.net/projects/hbci4java/files/hbci4java-server/0.2.0%28xmas-edition%29/hbci4java-server-0.2.0-src.zip/download) gibt es ein Zip mit den Sourcen von Version 0.2.0. Kann den allerdings nicht kompilieren - insb. MsgGen wird nicht gefunden und ein paar andere Hilfsmethoden scheinen entfernt oder umgezogen worden zu sein...

**Comment by bennaux** [comment]
Hm, MsgGen ist ja Bestandteil von der Clientversion, wenn ich mich nicht irre. Werde mir das mal anschauen!
