### ISSUE TITLE
Beispiel UmsatzAbrufPinTan funktioniert nicht

### ISSUE THREAD

**Issue by quadduc** [hbci4j/hbci4java#23]
Ich greife mittels des Beispiels in UmsatzAbrufPinTan.java auf eine Bank zu, bei der es Probleme beim Erstellen des HBCIHandlers gibt:
```
org.kapott.hbci.exceptions.HBCI_Exception: message is expected to be encrypted
9955:Ein-Schritt-TAN-Verfahren nicht zugelassen
9800:Dialog abgebrochen.
3060:Teilweise liegen Warnungen vor.
```
![image](https://user-images.githubusercontent.com/51818311/59497159-2d213b00-8e93-11e9-9aea-bea3091c0e8a.png)

Den Fehler bzgl. der Encryption sehe ich sehr häufig, daher vermute ich, dass der eigentlich Fehler in der zweiten Zeile (Fehler 9955) steckt -- ist die Vermutung korrekt?

Unterstützt HBCI4Java hier ein von der Bank benötigtes Feature nicht oder muss ich den Zugriff anders gestalten?

**Comment by willuhn** [comment]
Der Fehler "9955:Ein-Schritt-TAN-Verfahren nicht zugelassen" besagt, dass du der Bank ein TAN-Verfahren mitgeteilt hat, welches sie gar nicht anbietet. Das TAN-Verfahren ist die 3-stellige Ziffer, die mit 9 beginnt. Du darfst hier nicht einfach pauschal irgendeinen Wert senden sondern musst erst ermitteln, welche TAN-Verfahren die Bank unterstützt, dann eines davon auswählen und dieses dann an die Bank senden. Schau dir hierzu bitte mal den Callback in Zeile 316ff an. https://github.com/hbci4j/hbci4java/blob/master/src/main/java/org/kapott/hbci/examples/UmsatzAbrufPinTan.java#L316 Dort ist das näher beschrieben.
