### ISSUE TITLE
ING Banking no more possible

### ISSUE THREAD

**Issue by jhmgbl** [hbci4j/hbci4java#24]
With the 3.1.6 Version Banking is no more possible. "Unable to fetch SysID".

**Comment by willuhn** [comment]
Die ING hat mit der PSD2-Einführung FinTS quasi abgeschafft.
https://www.willuhn.de/wiki/doku.php?id=psd2#die_ing_schrieb_mir_mein_banking-programm_soll_die_psd2-api_verwenden

**Comment by willuhn** [comment]
Darüber hinaus kann es bis zum 14.09. bei der Bank zu Fehlern kommen, weil die die PSD2-fähige Version von deren FinTS-Server (der dann meines Wissens nach nur noch den Umsatzabruf unterstützen wird) noch nicht ausgerollt haben. Siehe https://twitter.com/subsembly/status/1171297351077642241 sowie https://www.willuhn.de/wiki/doku.php?id=psd2#meine_bank_unterstuetzt_psd2_noch_gar_nicht

**Comment by willuhn** [comment]
Nach aktuellem Stand hat die ING bis heute keinen PSD2-faehigen FinTS-Server ausgerollt. Vermutlich koennte man noch per HBCI+ mit denen kommunizieren. Ich sehe aber ehrlich gesagt nicht ein, in HBCI4Java Sonderbehandlungen für die einzige Bank in Deutschland einzubauen, die es nicht geschafft hat, ihre FinTS-Server PSD2-ready zu machen.

**Comment by inren** [comment]
Hallo,
ich verwende Hibiscus Server-Version: 2.8.10 [Build: 138] mit der ING um meine Umsätze zu holen und in einem eigenen Programm für mich aus zu werten. Die Umsätze und Konto Stände werden noch abgeholt wie in den letzten 3 Wochen. Früher hatte ich die CSV Dateien runter geladen, geparst und ausgewertet. Mit hbci4j selbst habe ich mich schwer getan und war frph jetzt so eine einfache Variante zu haben. Ich rufe die Umsätze per REST API vom Hibiscus Server ab. Funktioniert 1a. Danke für die Möglichkeit. Würde mich freuen, wenn das weiterhin möglich bleibt. Ich würde ungern wieder die CSV parsen müssen.

Jetzt ein aber. Gestern habe ich versucht den Server auf einen anderen Rechner und andere DB zu kopieren (Open Suse, gleiches JDK "1.8.0_121", mit übernommen). Allerdings habe ich es nicht mehr geschafft den Tan Zugang neu zu konfigurieren.  Da frage ich mich, liegt der Fehler eher auf meiner Seite oder ist das ein bekanntes Problem mit der DIBA aktuell und es ist Zufall, dass meine ältere Installation noch funktioniert. Log Auszug weiter unten.

Viele Grüße,
    Ingo Renner

[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Aktualisiere Bankparameter (BPD)
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Erzeuge HBCI-Nachricht DialogInitAnon
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Verbinde mit https://fints.ing-diba.de:443/fints/ und prüfe Zertifikat
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Versende HBCI-Nachricht
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Warte auf Antwortdaten
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Warte auf Antwortdaten
[Thu Sep 19 22:55:58 CEST 2019][ERROR][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Meldung der Bank: 9800:Der Dialog wurde abgebrochen. org.kapott.hbci.status.HBCIStatus.addRetVal(HBCIStatus.java:72)
[Thu Sep 19 22:55:58 CEST 2019][ERROR][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Meldung der Bank: 9400:Der anonyme Dialog wird nicht unterstützt. org.kapott.hbci.status.HBCIStatus.addRetVal(HBCIStatus.java:72)
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Überprüfe Signatur der Antwortnachricht
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Erzeuge HBCI-Nachricht DialogEndAnon
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Versende HBCI-Nachricht
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.status] Warte auf Antwortdaten
[Thu Sep 19 22:55:58 CEST 2019][INFO][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Warte auf Antwortdaten
[Thu Sep 19 22:55:58 CEST 2019][ERROR][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Meldung der Bank: 9800:Der Dialog wurde abgebrochen. org.kapott.hbci.status.HBCIStatus.addRetVal(HBCIStatus.java:72)
[Thu Sep 19 22:55:58 CEST 2019][ERROR][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] Meldung der Bank: 9110:Unbekannter Aufbau der Kundennachricht. org.kapott.hbci.status.HBCIStatus.addRetVal(HBCIStatus.java:72)
[Thu Sep 19 22:55:58 CEST 2019][ERROR][qtp1168760551-52][de.willuhn.jameica.hbci.payment.HBCICallbackServer.log] org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
        at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:428)

**Comment by willuhn** [comment]
Wende dich hierzu bitte ans Forum unter 
https://homebanking-hilfe.de/forum/index.php?f=33
Wie ich schon im Issue schrieb: Die Bank hat es als einzige nicht 
geschafft, PSD2 korrekt umzusetzen. Im Forum kann dir sicher jemand helfen.

Am 19. September 2019 23:13:37 schrieb Ingo Renner <notifications@github.com>:

**Comment by willuhn** [comment]
Der passende Thread dazu findet sich hier.

**Comment by inren** [comment]
Danke für den Link.
