### ISSUE TITLE
BIC/IBAN wird nicht mehr gespeichert

### ISSUE THREAD

**Issue by shred** [hbci4j/hbci4java#26]
Die BIC und IBAN scheint nicht mehr im Passport gespeichert zu werden. Mit folgenden Schritten macht sich das hier bemerkbar:

- Ich lösche eine eventuell vorhandene Passport-Datei.
- hbci4java generiert diese Datei bei der nächsten Transaktion neu. Im `Konto`-Objekt sind BIC und IBAN vorhanden. `Konto.isSEPAAccount()` liefert `true`.
- Ab der darauf folgenden Transaktion sind die BIC und IBAN im Konto-Objekt allerdings `null`, und `Konto.isSEPAAccount()` liefert `false`.
- Wenn ich die Passport-Datei lösche, ist die BIC und IBAN für die unmittelbar nächste Transaktion wieder vorhanden.

Ich verwende die Version 3.1.13. Mit der Version 3.0.8 hat das noch funktioniert, allerdings war diese anscheinend nicht PSD2-Kompatibel. Die Verbindung geht zur Sparkasse Köln/Bonn.

Den Kontoauszug kann ich trotzdem abholen. Ich weiß allerdings nicht, ob `Konto.bic` und `Konto.iban` für SEPA-Lastschriften und SEPA-Überweisungen benötigt werden. Oder kann man das Problem einfach ignorieren?

**Comment by willuhn** [comment]
BIC und IBAN werden durch den impliziten Aufruf des Geschäftsvorfalls "SEPAInfo" ausgeführt, welcher im Konstruktor von HBCIHandler per "updateMetaInfo" immer automatisch ausgeführt wird. Der Geschäftsvorfall schlägt seit PSD2 jedoch bei manchen Banken fehl. Daher fehlen diese Informationen schlicht. Eventuell liefert die Bank auch Null-Werte und GVSEPAInfo#extractResults übernimmt diese fälschlicherweise in Zeile 92. 

Kannst du das mal debuggen? Ich kann das bei meinem Konto nicht reproduzieren?

**Comment by shred** [comment]
Die BIC und IBAN wird für SEPA-Lastschriften benötigt:

`org.kapott.hbci.exceptions.InvalidUserDataException: property src.bic is not set`

Ich muss erst einmal schauen, dass ich die Lastschriften wieder ans Laufen bekomme. Danach werde ich versuchen zu debuggen.

**Comment by shred** [comment]
Hmm... Sobald ich eine eigene Version von hbci4java mit Debug-Ausgaben baue, erhalte ich von der Bank folgende Fehlermeldung:

`9078:Dialog abgebrochen - Banking-Programm ist nicht registriert.`

Muss ich beim Bauen irgendwas beachten?

**Comment by willuhn** [comment]
Du darfst keine eigene Produktbezeichnung beim Initialisieren von HBCI4Java angeben.

**Comment by shred** [comment]
Das mache ich nicht, zumindest nicht dass ich es wüsste. Ich habe in der pom die Version auf `3.9.9-SNAPSHOT` erhöht, dann mit `mvn clean install` das Projekt gebaut, dann diese Snapshot-Version als Dependency in die pom von unserem Server-Projekt eingetragen. Dieser Server bekommt dann den Fehler von der Bank. Stelle ich die Dependency auf die offizielle Version `3.1.13` zurück, geht alles wieder.

**Comment by willuhn** [comment]
Eine Version 3.9.9 gibt es von mir überhaupt nicht.

**Comment by shred** [comment]
Das ist richtig. Es ist auch nur ein Dummy. Ich brauche eine höhere Versionsnummer als die aktuelle 3.1.13, damit Maven meinen Build verwendet und nicht einen offiziellen von Maven Central.

**Comment by willuhn** [comment]
Ich weiss nicht, was du da falsch machst. Ich kenne ja denen Code nicht und mir fehlt auch die Zeit, das zu analysieren, weil ich seit 2 Wochen eigentlich den ganzen Tag damit beschaeftigt bin, Mails von Hibiscus-Usern zu beantworten. Die Fehlermeldung kommt jedenfalls, wenn die Produktregistrierung nicht gesendet wird. Wenn es mit 3.1.13 geht, dann finde heraus, was du selbst geändert hast.

Sorry, aber ich kann wirklich nicht jedem helfen. Ich kriege hier ca. 100 Mails täglich. Ich mache nichts anderes mehr, als anderen zu helfen. Ich will trotz PSD2 irgendwann auch mal wieder ein eigenes Leben haben. Bitte versuche das Problem selbst zu lösen.

**Comment by shred** [comment]
Okay, ich schaue, was ich machen kann. Bitte vergiss nicht, dass ich auf deiner Seite stehe und gerade versuche, ein Problem mit der Sparkasse in den Griff zu bekommen, was möglicherweise auch ein Teil deiner 100 Mails pro Tag lösen würde. :smile:

**Comment by willuhn** [comment]
Ehrlich gesagt weiss ich von keinem Sparkassen-Problem mit Hibiscus. Ich habe selbst auch ein Sparkassen-Konto, welches problemlos funktioniert. Und im Forum finden sich zu Sparkassenproblemen auch fast keine Threads. Direkt für Hibiscus sind mir kein Probleme mit den Sparkassen bekannt.

**Comment by shred** [comment]
Ich konnte die Stelle lokalisieren. In `AbstractHBCIPassport.getAccounts()` Zeile 267 wird die IBAN aus `KInfo.KTV.iban` und die BIC aus `KInfo.KTV.bic` ermittelt. Diese Felder existieren in der `upd`-Properties nur, wenn ich die Passport-Datei gerade gelöscht habe.

Bei jedem weiteren Mal, wenn `getAccounts()` aufgerufen wird, gibt es in der `upd`-Properties nur noch ein Feld `KInfo.iban` (ohne `KTV`), eine BIC steht in den Properties gar nicht mehr.

Als Resultat haben im `Konto`-Objekt `bic` und `iban` dann den Wert `null`.

Mir fehlt die Erfahrung mit dem Projekt, um entscheiden zu können, wie ich das Problem am besten lösen kann. Ich würde das Feld `KInfo.iban` auslesen, wenn `KInfo.KTV.iban` nicht existiert, und den übrigen Code fit machen, dass eine BIC nicht mehr für SEPA-Transaktionen erforderlich ist. Was meinst du?

**Comment by willuhn** [comment]
Sicher, dass du Zeile 267 meinst? An der Stelle ist doch gar nichts mit IBAN.

**Comment by shred** [comment]
Sorry, meine IDE hat die Importe aufgeräumt. Es ist Zeile 248.

Ich konnte es weiter herunterbrechen auf `HBCIUser.updateUPD()`. In der dort übergebenen Properties (die vermutlich von der Bank kommt) gibt es nur `UPD.KInfo.iban` und keine BIC.

**Comment by willuhn** [comment]
Unabhängig davon: Es gibt - wie ich schon schrieb - nur eine einzige Stelle, wo IBAN und BIC in die UPD geschrieben wird. Nämlich in GVSEPAInfo#extractResults. Seit PSD2 schlägt dieser Aufruf bei manchen Banken fehl. Unter Umsänden auch nur manchmal. Ich hatte das daher jetzt so geändert, dass die IBAN und BIC nur noch dann in die UPD übernommen wird, wenn etwas drin steht.

Damit sollte es nicht mehr passieren, dass bei Fehlschlag des IBAN/BIC-Abrufs in GVSEPAInfo die Daten in den UPD überschrieben werden.

https://github.com/hbci4j/hbci4java/commit/ecea961ceda3f259f14ad1d0bc442b2b58bed6e5

**Comment by willuhn** [comment]
Wo "KInfo.iban" herkommt, weiss ich aber nicht. Ich finde keine einzige Stelle, wo das in der Form in die UPD geschrieben wird.

**Comment by shred** [comment]
ecea961 löst mein Problem leider nicht. Das Fehlerbild ist unverändert. Ich rufe `GVKUmsAll` auf, welcher nicht von `GVSEPAInfo` abgeleitet ist, so dass die Änderung auch nicht aufgerufen wird.

Anscheinend ist nach dem `GVKUmsAll` die bic/iban weg. Andere Geschäftsvorfälle kann ich leider nicht prüfen, ohne mir vorher eine Testumgebung aufzusetzen.

**Comment by willuhn** [comment]
Es geht nicht darum, ob ein GV von GVSEPAInfo abgeleitet ist. Der GV wird in HBCIHandler aufgerufen. Aber wenn er fehlschlägt, weil die Bank das wegen PSD2 aus einem mir unbekannten Grund ablehnt, dann wird die IBAN nicht abgerufen.

**Comment by shred** [comment]
Zu meinem PR: Ich setze an der Methode `HBCIUser.updateUPD()` an. Wenn die dort übergebenen `Properties` keine BIC/IBAN mehr haben, im alten `upd` die Informationen aber noch vorhanden sind, übertrage ich sie einfach in die neue `upd`.

Ich mache vorher eine Prüfung, ob die Bankverbindung (Land, BLZ, Kontonummer) identisch sind, um zu verhindern, dass bei einer wirklichen Änderung der Daten eine falsche BIC/IBAN "mitgeschleppt" wird.

Der Stacktrace an der Stelle, an der bei mir eine Properties ohne BIC/IBAN reinkommt, ist:

```
	at org.kapott.hbci.manager.HBCIUser.updateUPD(HBCIUser.java:596)
	at org.kapott.hbci.manager.HBCIDialog.doDialogInit(HBCIDialog.java:126)
	at org.kapott.hbci.manager.HBCIDialog.doIt(HBCIDialog.java:430)
	at org.kapott.hbci.manager.HBCIHandler.execute(HBCIHandler.java:504)
```

Es passiert also beim Dialog-Init. Wenn ich das richtig sehe, kommt das UPD ohne die BIC/IBAN also von der Bank.

**Comment by shred** [comment]
Sorry, ich brauche noch einmal deine Entscheidung. Mir hat die Sache keine Ruhe gelassen und ich habe weitergesucht.

Vor dem Einreichen einer Lastschrift rufe ich `Konto.isSEPAAccount()` auf, um sicherzustellen, dass ich die SEPA-Lastschrift auf einem SEPA-fähigen Konto durchführe. Dieser Test hat bisher stets funktioniert. Seit PSD2 liefert `.isSEPAAccount()` allerdings `false`, und mein Code steigt dann mit einer Exception aus.

Ich habe jetzt Version 3.1.17 getestet (das ist die letzte Version vor meinem PR) und die `.isSEPAAccount()`-Prüfung in meinem Code entfernt. Es funktioniert damit. Du hast das Problem also tatsächlich zwischenzeitlich gefixed.

Jetzt ist die Frage: Soll ich einen PR einreichen, der meinen anderen PR rückgängig macht? Damit arbeitet die `.isSEPAAccount()`-Methode allerdings nicht mehr zuverlässig. Oder lassen wir den PR drin?

Die Methode `Konto.isSEPAAccount()` wird in hbci4java sowieso nirgendwo benutzt. Wenn ich meinen PR rückgängig mache, könnte ich sie bei der Gelegenheit als deprecated markieren und entsprechend als unzuverlässig kommentieren.

**Comment by willuhn** [comment]
Ich wuerde es drin lassen. Schadet ja nicht. Und ich koennte mir durchaus vorstellen, dass es noch Szenarien gibt, in denen die Bank wegen fehlender SCA die UPD ohne Konto-Informationen sendet. Das isSEPAAccount() würde ich auch drin lassen und auch nicht deprecated markieren. Die Methode hat ja ihre Daseinsberechtigung. Was ich aber nicht verstehe ist, warum diese Funktion jetzt unzuverlässig sein sollte. Die prüft doch nur, ob BIC und IBAN im Konto vorhanden ist. Wenn die unerwartet false liefert, wäre doch eher der Fehler, dass BIC und IBAN im Konto fehlen. Wenn dein Geschäftsvorfall trotzdem funktioniert, müsste man mal den konkreten Fall prüfen. Also wie genau du da die Parameter "My.bic" und "My.iban" setzt. Eventuell nimmst du die ja gar nicht aus dem Konto sondern von woanders.

**Comment by shred** [comment]
Wie gesagt: Die BIC und IBAN sind zuerst da, wenn der Passport angelegt wird, verschwinden aber mit der nächsten Transaktion aus dem Konto, wenn man es nicht (wie in meinem Patch) verhindert. Unser HBCI-Server hier ist nur mit der BLZ und Kontonummer konfiguriert. Die zugehörige BIC und IBAN muss also an irgendeiner Stelle von der Bank übermittelt werden, während der Passport angelegt wird.

Ist aber egal... Der HBCI-Server funktioniert hier wieder, und mein Patch könnte tatsächlich jemandem helfen, auf jeden Fall aber nicht schaden. Von meiner Seite können wir es dabei belassen.

Danke für deine Hilfe! :smile:

**Comment by willuhn** [comment]
Die BIC und IBAN wird per HKSPA abgerufen. Der GV heisst "SEPAInfo" und wird in HBCIHandler#updateMetaInfo automatisch aufgerufen, wenn der Handler instanziiert wird. Ich nehme an, dass es zu dem Problem kam, wenn bei der Auswertung des GV die Werte pauschal in die UPD übernommen wurden, ohne zu prüfen, ob überhaupt Daten vorhanden sind. Das geschieht in GVSEPAInfo#extractResults mit 

upd.setProperty(temp_header+".KTV.iban", iban);
upd.setProperty(temp_header+".KTV.bic", bic);

Dort hatte ich jeweils ein "if (StringUtil.hasText(iban|bic))" davor eingefügt. Das war mein Fix des Problems. Der Code hatte IBAN und BIC also gezielt aus den UPD rausgeloescht.
