### ISSUE TITLE
Unterstützung für SEPA Echtzeitüberweisung (HKIPZ)

### ISSUE THREAD

**Issue by dankito** [hbci4j/hbci4java#29]
Hallo,

es wäre klasse, wenn Sie zusätzlich den Geschäftsvorfall SEPA Instant Payment Zahlung (HKIPZ) unterstützen könnten.

Ich habe versucht ihn selbst zu implementieren, bin jedoch daran gescheitert, dass ich die Spezifikation nicht verstehe (angehängt als [CR0482_Anl_Unterstuetzung_von_Instant_Payments_in_FinTS_final-version.pdf](https://github.com/hbci4j/hbci4java/files/3638616/CR0482_Anl_Unterstuetzung_von_Instant_Payments_in_FinTS_final-version.pdf)).

Ich hätte ein Beispiel zum Tätigen von SEPA Überweisungen (UebSEPA / HKCCS) vergleichbar zu UmsatzAbrufPinTan implementiert.
Soll ich es verallgemeinern und Ihnen einen Pull Request stellen, so dass Sie es zusammen mit dem Umsätze abrufen Beispiel veröffentlichen können?

**Comment by willuhn** [comment]
Fuer neue Geschaeftsvorfaelle fehlt mir bis auf weiteres die Zeit. Wegen PSD2 sind noch eine ganze Menge anderer Themen derzeit wichtiger.
