### ISSUE TITLE
SEPA Infos werden nicht abgerufen

### ISSUE THREAD

**Issue by styppo** [hbci4j/hbci4java#34]
Seit Commit c183d72069e99e1fc3f722caa3b80ed30a7f6894 werden SEPA Infos nur abgerufen, wenn die Bank dies unterstützt. Dazu prüft [`HBCIDialogSepaInfo.supported()`](https://github.com/hbci4j/hbci4java/commit/c183d72069e99e1fc3f722caa3b80ed30a7f6894#diff-90e905efadad730860db0c2629e5422aR61) die höchste verfügbare Version des `SEPAInfo` Segments mithilfe von [`AbstractRawHBCIDialog.getSegmentVersion()`](https://github.com/hbci4j/hbci4java/commit/c183d72069e99e1fc3f722caa3b80ed30a7f6894#diff-1bba2d8906416b9cb72edc2e7accfbd7R185). Diese Methode wurde in besagtem Commit (fast) unverändert aus `HBCIDialogTanMedia` übernommen und unterstützt nur Versionsnummern zwischen `2` und `5`. Die höchste Versionsnummer des `SEPAInfo` Segments scheint allerdings `1` zu sein, was zum Fehlschlagen der `supported()`-Prüfung und zum Abbruch des Info-Abrufs führt.

**Comment by willuhn** [comment]
Hoppla. Danke für die Analyse und das Patch.
