### ISSUE TITLE
HITAB #5: TAN-Medium-Klasse 'B'

### ISSUE THREAD

**Issue by oheim** [hbci4j/hbci4java#39]

**Comment by oheim** [comment]
In TANMediaInfo5.mediacategory fehlt der neue gültige Wert 'B' für „bilateral vereinbart“
https://github.com/hbci4j/hbci4java/blob/master/src/main/resources/hbci-300.xml#L2047

Vgl. auch TANMediaList5.mediacategory, wo der neue Wert bereits definiert wurde.

**Comment by willuhn** [comment]
Danke fuer den Hinweis. Magst du mir die Aenderung gleich als Pull-Request auf dem Master-Branch senden?

**Comment by oheim** [comment]
#40
