### ISSUE TITLE
passport.getAccounts() enthält keine BIC/IBAN Informationen der Konten

### ISSUE THREAD

**Issue by PetePriority** [hbci4j/hbci4java#41]
Ich benutze den Beispielcode von `UmsatzAbrufPinTan.java` um die Umsaetze meiner Konten abzurufen. Nach dem (Neu-)anlegen des Passports gibt `passport.getAccounts()` die Konten mit BIC/IBAN zurück. Bei allen weiteren Aufrufen sind die IBAN und BIC Felder der Konten jedoch  `null`.

Verwendete Version: 3.1.37

Bank: Consorsbank (BLZ 76030080)

Erwartetes Verhalten: Die Konten von passport.getAccounts() haben immer die BIC/IBAN gesetzt und sind nicht `null`.

Hört sich sehr nach #26 an.

**Comment by willuhn** [comment]
Ich befürchte, du wirst den Bug selbst analysieren und fixen müssen. Ich kann den Fehler nicht reproduzieren und in #26 wurde ja bereits ein Mechanismus eingebaut, der genau das Verhalten verhindern soll.

**Comment by shred** [comment]
Ich kann nur bestätigen, dass ich das gleiche Problem hatte, es aber mit dem Fix für #26 behoben wurde. Der Fix ist an der einzigen Stelle, die ich fand, welche eine BIC/IBAN nachträglich im Passport ändern konnte.

Zum Debuggen würde ich an der Stelle, die ich in #30 gepatcht habe, ansetzen. Der Code prüft zuerst, ob die BLZ, Kontonummer und das Land unverändert sind. Erst dann übernimmt er die BIC/IBAN aus dem vorherigen Passport. Das soll sicher stellen, dass keine veraltete BIC/IBAN mitgeschleppt wird, falls sich das Konto geändert hat. Vielleicht scheitert diese Prüfung bei dir?

Viel weiterhelfen kann ich sonst leider nicht, da ich wegen eines Jobwechsels keinen Zugang mehr zu einem HBCI-Server habe.
