### ISSUE TITLE
Saldo in GVKUmsAllCamt wird falsch fortgeschrieben, wenn es mehr als eine Nachricht gibt

### ISSUE THREAD

**Issue by geesen** [hbci4j/hbci4java#42]
Wenn beim Abruf der Umsätze über GVKUmsAllCamt mehr als eine XML-Nachricht kommt, dann werden die Salden ab der zweiten Nachricht falsch addiert. 

Wenn ich bei einer Volksbank mehr als 150 Buchungen habe, dann laufen in GVKUmsAllCamt#extractResults mehr als eine XML-Nachricht auf, die geparst werden. 
Bei der zweiten Nachricht wird dann aber beim laufenden Saldo nicht bei dem im XML-Header angegeben Startsaldo angefangen, sondern bei 0,00 €. 
Wenn also die 150. Buchung z.B. - 10,00 € und der laufende Saldo danach 150,00 € ist, stimmt es noch. Kommt nun eine 151. Buchung hinzu, mit z.B. - 50,00 €, dann ist der laufende Saldo danach -50,00 € und nicht 100,00 €. 
Ich vermute, dass dieser Fall nur auftritt, wenn zwei camt-Nachrichten als Antwort kommen und der Buchungsdaten am Ende der ersten Nachricht auch am Anfang der zweiten Nachricht vorkommt.

Soweit ich das nachvollziehen kann, liegt dies an folgender Stelle im Parser:

https://github.com/hbci4j/hbci4java/blob/510cb71d4d57fe7361199b3fa7e25186b15b61fa/src/main/java/org/kapott/hbci/GV/parsers/ParseCamt05200102.java#L305

In der zweiten Nachricht gibt es nämlich kein Anfangssaldo (PRCD), sondern nur ein Zwischensaldo (ITBD). Somit wird `tag.start` nie gesetzt und man müsste die Zwischensalden auch in den Parsern berücksichtigen.

Ein einfaches Ändern in:
```java
 if (code == BalanceType12Code.PRCD || code == BalanceType12Code.ITBD) 
```
sollte aber nicht die Lösung sein, wenn man die entsprechende Erklärung aus der Spezifikation liest:

> Erste camt.053-Nachricht:
Erster Saldo „PRCD“ und zweiter Saldo „ITBD“
Weitere camt.053-Nachrichten (falls erforderlich):
Erster und zweiter Saldo jeweils „ITBD“
Letzte camt.053-Nachricht:
Erster Saldo „ITBD“ und zweiter Saldo „CLBD“

Somit müsste man unterscheiden, ob es der erste oder der zweite Saldo ist und dann entsprechend `start` und `end` setzen - da bin ich mir aber nicht ganz sicher, ob das immer so mit der Reihenfolge so ist und dass es immer zwei Salden gibt?!

**Comment by willuhn** [comment]
Du kannst mir hierzu gern einen Pull-Request erstellen. Bei mir trat noch nie der Fall auf, dass ich mehrere Camt-Dateien hatte. Von daher habe ich keine Testmöglichkeiten. Erstelle doch einfach einen PR, der den Code so ändert, dass es bei dir passt. Das wäre dann ja allemal besser als jetzt.

**Comment by willuhn** [comment]
Danke für das Patch. Habs gemerged.
