### ISSUE TITLE
ParseErrorException: CryptedRes.CryptHead.SegHead.code: vorgegebener Wert "HNVSK" stimmt nicht mit gefundenem Wert "HIRMG" überein

### ISSUE THREAD

**Issue by thimo-seitz** [hbci4j/hbci4java#45]
Hallo.

Bei dem aktuellen Release (3.1.42) bekomme ich eine `ParseErrorException` mit dem Inhalt `CryptedRes.CryptHead.SegHead.code: vorgegebener Wert "HNVSK" stimmt nicht mit gefundenem Wert "HIRMG" überein`

Die Exception wird an dieser Stelle in Zeile 228 konstruiert:
![grafik](https://user-images.githubusercontent.com/20231368/88795313-1e353f00-d1a0-11ea-8006-2483a17269c5.png)
![grafik](https://user-images.githubusercontent.com/20231368/88795907-12964800-d1a1-11ea-84bd-9a08f7680a53.png)

Ist hier die Nachricht von der Bank falsch aufgebaut, oder hat die Verabeitung der Lib einen Fehler?

Beste Grüße
Thimo Seitz

**Comment by willuhn** [comment]
Sorry. Irgendwie ist das Issue "untergegangen". Hat sich hier inzwischen etwas neues ergeben?

**Comment by willuhn** [comment]
Ich schliesse das Ticket, weil hier keine Antwort mehr kam.
