### ISSUE TITLE
Crash nach Windows Update 

### ISSUE THREAD

**Issue by mabaumga** [hbci4j/hbci4java#46]
Ich habe heute auf Windows 10 Version 2004 aktualisiert.

Seitdem funktioniert mein Chipkartengerät (CyberJack Standard) nicht mehr. Will ich diesen nutzen, dann crasht die JVM. 

Liegt anscheinend an der Datei hbci4java-card-win32_x86-64.dll

Siehe Logdatei:

[crash.log](https://github.com/hbci4j/hbci4java/files/5113107/crash.log)

**Comment by willuhn** [comment]
Die Verwendung von PC/SC ist die korrekte Lösung. Im Prinzip könnte der CTAPI-Support aus Hibiscus entfernt werden. Allerdings wird es noch von vielen Usern genutzt.
