### ISSUE TITLE
Angabe von Adressdaten bei SEPA Lastschrift in Drittstaaten

### ISSUE THREAD

**Issue by kicktipp** [hbci4j/hbci4java#47]
Bei einer SEPA Lastschrift in Drittstatten (wie Schweiz und seit dem Brexit eventuell auch UK) muss man laut Sepa Abkommen die Adresse des Schuldners angeben. Dazu stehen zwei Adresszeilen mit max 70 Zeichen und die Angabe des Landes zur Verfügung.

https://groups.google.com/g/hbci4java/c/shoSh1Oo8eo/m/76t3QRy2BQAJ?pli=1

**Comment by kicktipp** [comment]
https://github.com/hbci4j/hbci4java/pull/48
Würde das so grundsätzlich funktionieren?

**Comment by willuhn** [comment]
PR gemerged. Hab die Änderung auch noch bei den anderen PAIN-Versionen übernommen und ein neues Release 3.1.50 erstellt - Upload läuft gerade.
