### ISSUE TITLE
Status Echtzeitueberweisungen?

### ISSUE THREAD

**Issue by pbl987** [hbci4j/hbci4java#54]
Gibt es schon ein ETA zu Echtzeitueberweisungen? 
Das ist das einzige Feature, was ich noch vermisse.
Waere schade, wenn ich nur deswegen eine Banking-Software kaufen muss.

**Comment by willuhn** [comment]
SEPA Instant-Payments sind mit dem GV "InstUebSEPA" schon seit über 1 Jahr implementiert.

**Comment by pbl987** [comment]
Oh, ok. Wie kann ich dann eine Ueberweisung abschicken? In Jameica habe ich nichts gefunden, ebenso im Handbuch.

**Comment by pbl987** [comment]
PS: Man kann dir in github keine Emails schreiben. Schade.

**Comment by willuhn** [comment]
Unter https://homebanking-hilfe.de/forum/index.php?f=33 findest du das User-Forum von Hibiscus.

**Comment by pbl987** [comment]
> hibiscus	
> Betreff: Re: SEPA Instant-Transfer über HBCI  ·  Gepostet: 29.03.2020 - 17:41 Uhr  ·  #7
> Nein, leider noch keine Neuigkeiten. 

Das ist letzte von drei Nachrichten, die zu dem Thema gepostet ist.

Deine erste Antwort deutet an, dass das geht.
Ist es zu viel verlangt, mir eine kurze und abschliessende Antwort zu geben?
_- Ja, es geht. Im Menuepunkt unter...
- Nein, es geht nocht nicht und wird noch n Jahre dauern._

**Comment by kicktipp** [comment]
Die Antwort bisher war doch klar: Du sollst die Antwort zu deiner Frage im 
Forum der Software jameica suchen. Hier bist du mit deiner Frage falsch. 
Hier geht es nicht um jameica, sondern um hbci4java

Und: Das ist hier ein Open source Projekt. Verlangen kann man daher erstmal 
gar nichts. Schon gar nicht von willhuhn, der hier die gesamte Arbeit leistet.

Folge daher bitte einfach dem Link zum Forum.

Gruß
Janinng



Am 8. März 2021 22:05:39 schrieb pbl987 <notifications@github.com>:

**Comment by willuhn** [comment]
Wow. That escalated quickly.
