### ISSUE TITLE
ING DiBa Connection

### ISSUE THREAD

**Issue by levitin** [hbci4j/hbci4java#56]
The connection to ING-DiBa fails, probably since they have switched to PSD2 procedure.

<details>
<summary>Here is a very simplified source code section</summary>

```java
private final static HBCIVersion VERSION = HBCIVersion.HBCI_PLUS;

    public static void main(String[] args) throws Exception {
        Properties props = new Properties();
        HBCIUtils.init(props, new HBCICallbackConsole());

        HBCIPassport passport = new HBCIPassportPinTanMemory(null);
        passport.setHost(HBCIUtils.getBankInfo(BLZ).getPinTanAddress());

        HBCIHandler handle = null;

        try {
            handle = new HBCIHandler(VERSION.getId(), passport);
            Konto[] accounts = passport.getAccounts();
            System.out.println(Arrays.toString(accounts));
        } finally {
            if (handle != null) {
                handle.close();
            }
        }
    }
```
</details>

<details>
<summary>Log outputs</summary>
Callback für Passport mit Init-Daten: null
Bankleitzahl []: 50010517
Callback für Passport mit Init-Daten: null
Länderkennzeichen (DE für Deutschland) [DE]: 
Callback für Passport mit Init-Daten: null
Hostname/IP-Adresse [fints.ing.de/fints/]: 
Callback für Passport mit Init-Daten: null
Portnummer (3000) [443]: 
Callback für Passport mit Init-Daten: null
Komm.-Filter ("None"/"Base64") [Base64]: 
Callback für Passport mit Init-Daten: null
Nutzerkennung []: xxxxxxxxxx
Callback für Passport mit Init-Daten: null
Kunden-ID [xxxxxxxxxx]: 
hole kreditinstituts-spezifische Daten
  Erzeuge HBCI-Nachricht DialogInitAnon
<WRN> [2021.04.28 16:18:36.561] [main/main] protocol.MSG: could not insert the following user-defined data into message: DialogInitAnon.TAN2Step6=requested
<WRN> [2021.04.28 16:18:36.577] [main/main] protocol.MSG: could not insert the following user-defined data into message: DialogInitAnon.TAN2Step6.ordersegcode=HKIDN
<WRN> [2021.04.28 16:18:36.577] [main/main] protocol.MSG: could not insert the following user-defined data into message: DialogInitAnon.TAN2Step6.process=4
Callback für Passport mit Init-Daten: null
Bitte stellen Sie jetzt die Verbindung zum Internet her
<ENTER> drücken, um fortzufahren

  Versende HBCI-Nachricht
Sende HBCI-Nachricht: HNHBK:1:3+000000000125+220+0+1'HKIDN:2:2+280:50010517+9999999999+0+0'HKVVB:3:2+0+0+0+36792786FA12F235F04647689+3'HNHBS:4:1+1'
  Warte auf Antwortdaten
HBCI-Nachricht empfangen: HNHBK:1:3+000000000201+220+000006GOR2B41NDC62T81JJPMOCIT5+1+000006GOR2B41NDC62T81JJPMOCIT5:1'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9400::Der anonyme Dialog wird nicht unterstützt.'HNHBS:3:1+1'
  Lese empfangene Antwortnachricht (CryptedRes))
  Lese empfangene Antwortnachricht (DialogInitAnonRes))
HBCI-Nachricht empfangen und entschlüsselt: HNHBK:1:3+000000000201+220+000006GOR2B41NDC62T81JJPMOCIT5+1+000006GOR2B41NDC62T81JJPMOCIT5:1'HIRMG:2:2+9800::Der Dialog wurde abgebrochen.+9400::Der anonyme Dialog wird nicht unterstützt.'HNHBS:3:1+1'
<ERR> [2021.04.28 16:18:39.020] [main/main] status.HBCIStatus: Meldung der Bank: 9800:Der Dialog wurde abgebrochen.
<ERR> [2021.04.28 16:18:39.020] [main/main] status.HBCIStatus: Meldung der Bank: 9400:Der anonyme Dialog wird nicht unterstützt.
  Überprüfe Signatur der Antwortnachricht
  Erzeuge HBCI-Nachricht DialogEndAnon
  Versende HBCI-Nachricht
Sende HBCI-Nachricht: HNHBK:1:3+000000000055+220+0+2'HKEND:2:1+0'HNHBS:3:1+2'
  Warte auf Antwortdaten
HBCI-Nachricht empfangen: HNHBK:1:3+000000000165+220+unbekannt+9999+unbekannt:9999'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9110::Unbekannter Aufbau der Kundennachricht.'HNHBS:3:1+9999'
  Lese empfangene Antwortnachricht (CryptedRes))
  Lese empfangene Antwortnachricht (DialogEndAnonRes))
HBCI-Nachricht empfangen und entschlüsselt: HNHBK:1:3+000000000165+220+unbekannt+9999+unbekannt:9999'HIRMG:2:2+9800::Der Dialog wurde abgebrochen.+9110::Unbekannter Aufbau der Kundennachricht.'HNHBS:3:1+9999'
<ERR> [2021.04.28 16:18:39.152] [main/main] status.HBCIStatus: Meldung der Bank: 9800:Der Dialog wurde abgebrochen.
<ERR> [2021.04.28 16:18:39.152] [main/main] status.HBCIStatus: Meldung der Bank: 9110:Unbekannter Aufbau der Kundennachricht.
<ERR> [2021.04.28 16:18:39.152] [main/main] manager.HBCIUtils: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:428)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:176)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.sendData(AbstractRawHBCIDialog.java:123)
	at org.kapott.hbci.dialog.HBCIDialogEnd.sendData(HBCIDialogEnd.java:95)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:96)
	at org.kapott.hbci.manager.HBCIInstitute.fetchBPD(HBCIInstitute.java:283)
	at org.kapott.hbci.manager.HBCIInstitute.register(HBCIInstitute.java:373)
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:153)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:131)
	at io.levitin.hbci.Diba.main(Diba.java:42)
Dialog beendet
status: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
9800:Der Dialog wurde abgebrochen.
9110:Unbekannter Aufbau der Kundennachricht.
<WRN> [2021.04.28 16:18:39.152] [main/main] dialog.HBCIDialogEnd: dialog end failed: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
9800:Der Dialog wurde abgebrochen.
9110:Unbekannter Aufbau der Kundennachricht.
<ERR> [2021.04.28 16:18:39.152] [main/main] manager.HBCIUtils: org.kapott.hbci.exceptions.ProcessException: Dialog-Ende fehlgeschlagen
	at org.kapott.hbci.dialog.HBCIDialogEnd.checkResult(HBCIDialogEnd.java:124)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:106)
	at org.kapott.hbci.manager.HBCIInstitute.fetchBPD(HBCIInstitute.java:283)
	at org.kapott.hbci.manager.HBCIInstitute.register(HBCIInstitute.java:373)
	at org.kapott.hbci.manager.HBCIHandler.registerInstitute(HBCIHandler.java:153)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:131)
	at io.levitin.hbci.Diba.main(Diba.java:42)
<ERR> [2021.04.28 16:18:39.152] [main/main] manager.HBCIInstitute: fetching BPD failed: 9800:Der Dialog wurde abgebrochen.
9400:Der anonyme Dialog wird nicht unterstützt.
Callback für Passport mit Init-Daten: null
Sie können die Internetverbindung jetzt beenden
<ENTER> drücken, um fortzufahren

<WRN> [2021.04.28 16:18:40.404] [main/main] manager.HBCIInstitute: can not check if requested parameters are supported
hole neue System-ID
  Erzeuge HBCI-Nachricht Synch
<WRN> [2021.04.28 16:18:40.407] [main/main] protocol.MSG: could not insert the following user-defined data into message: Synch.TAN2Step6.process=4
<WRN> [2021.04.28 16:18:40.407] [main/main] protocol.MSG: could not insert the following user-defined data into message: Synch.TAN2Step6.ordersegcode=HKIDN
<WRN> [2021.04.28 16:18:40.407] [main/main] protocol.MSG: could not insert the following user-defined data into message: Synch.TAN2Step6=requested
  signiere HBCI-Nachricht
Callback für Passport mit Init-Daten: null
Bitte geben Sie die PIN für das PIN/TAN-Verfahren ein: xxxxxxxxxx
<WRN> [2021.04.28 16:18:45.810] [main/main] passport.HBCIPassportPinTan: the job with the code HNSHK seems not to be allowed with PIN/TAN
<WRN> [2021.04.28 16:18:45.810] [main/main] passport.HBCIPassportPinTan: the job with the code HKIDN seems not to be allowed with PIN/TAN
<WRN> [2021.04.28 16:18:45.811] [main/main] passport.HBCIPassportPinTan: the job with the code HKVVB seems not to be allowed with PIN/TAN
<WRN> [2021.04.28 16:18:45.812] [main/main] passport.HBCIPassportPinTan: the job with the code HKSYN seems not to be allowed with PIN/TAN
  Verschlüssele HBCI-Nachricht
<WRN> [2021.04.28 16:18:45.814] [main/main] protocol.MSG: could not insert the following user-defined data into message: Crypted.CryptHead.SecProfile.method=PIN
<WRN> [2021.04.28 16:18:45.814] [main/main] protocol.MSG: could not insert the following user-defined data into message: Crypted.CryptHead.SecProfile.version=1
Callback für Passport mit Init-Daten: null
Bitte stellen Sie jetzt die Verbindung zum Internet her
<ENTER> drücken, um fortzufahren

  Versende HBCI-Nachricht
Sende HBCI-Nachricht: HNHBK:1:3+000000000384+220+0+1'HNVSK:998:2+998+1+1::0+1:20210428:161845+2:2:13:@8@        :5:1+280:50010517:xxxxxxxxxx:V:0:0+0'HNVSD:999:1+@227@HNSHK:2:3+999+1958439477+1+1+1::0+1+1:20210428:161840+1:999:1+6:10:16+280:50010517:xxxxxxxxxx:S:0:0'HKIDN:3:2+280:50010517+xxxxxxxxxx+0+1'HKVVB:4:2+0+0+0+36792786FA12F235F04647689+3'HKSYN:5:2+0'HNSHA:6:1+1958439477++xxxxxxxxxx''HNHBS:7:1+1'
  Warte auf Antwortdaten
HBCI-Nachricht empfangen: HNHBK:1:3+000000001596+220+000006GOR2SVL38T4NJBB70723MNHI+1+000006GOR2SVL38T4NJBB70723MNHI:1'HNVSK:998:2+998+1+2::0+1+2:2:13:@8@        :6:1+280:50010517:xxxxxxxxxx:V:0:0+0'HNVSD:999:1+@1391@HIRMG:2:2:+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Angemeldet.'HIRMS:4:2:4+0020::Informationen fehlerfrei entgegengenommen.+3050::BPD nicht mehr aktuell. Aktuelle Version folgt.+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer:900'HIRMS:5:2:5+0020::Die Synchronisierung der Kundensystem-ID war erfolgreich.'HIBPA:6:2:4+7+280:50010517+ING-DiBa+0+1+220:300+200'HIKOM:7:3:4+280:50010517+1+3:https?://fints.ing-diba.de/fints/'HISPAS:8:1:4+1+1+0+J:J:J:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03'HIPAES:9:1:4+1+1+0'HICCSS:10:1:4+1+1+0'HITANS:11:1:4+1+1+0+J:N:0:0:900:2:iTAN:iTAN:6:1:Index:3:1:N:N'HIKAZS:12:5:4+1+1+390:N:N'HICDNS:13:1:4+1+1+1+0:1:360:J:J:J:J:J:N:N:N:J:00:00::0'HICSBS:14:1:4+1+1+0+N:N'HICSAS:15:1:4+1+1+0+1:360'HIWPDS:16:6:4+1+1+0+N:N:N'HIWPDS:17:5:4+1+1+N:N:N'DIPAES:18:1:4+1+1'HICDLS:19:1:4+1+1+1+1:360:N:J'HIPROS:20:3:4+1+1'HICSES:21:1:4+1+1+0+1:360'HICSLS:22:1:4+1+1+0+J'HICDBS:23:1:4+1+1+0+N'HISALS:24:5:4+1+1'HICDES:25:1:4+1+1+1+4:1:360:00:00::0'DIPINS:26:1:4+1+1+HKSPA:N:HKPAE:J:HKCCS:J:HKTAN:N:HKKAZ:N:HKCDN:J:HKCSB:N:HKCSA:J:HKWPD:N:DKPAE:J:HKCDL:J:HKPRO:N:HKCSE:J:HKCSL:J:HKCDB:N:HKSAL:N:HKCDE:J'HIPINS:27:1:4+1+1+0+5:10:6:Kontonummer::HKSPA:N:HKPAE:J:HKCCS:J:HKTAN:N:HKKAZ:N:HKCDN:J:HKCSB:N:HKCSA:J:HKWPD:N:DKPAE:J:HKCDL:J:HKPRO:N:HKCSE:J:HKCSL:J:HKCDB:N:HKSAL:N:HKCDE:J'HISYN:28:3:5+000006GOR2T4D4VOCV9LOK35FFF5EJ''HNHBS:29:1+1'
  Lese empfangene Antwortnachricht (CryptedRes))
  Entschlüssele Antwortnachricht
HBCI-Nachricht empfangen und entschlüsselt: HNHBK:1:3+000000001596+220+000006GOR2SVL38T4NJBB70723MNHI+1+000006GOR2SVL38T4NJBB70723MNHI:1'HIRMG:2:2:+3060::Teilweise liegen Warnungen/Hinweise vor.'HIRMS:3:2:3+0020::Angemeldet.'HIRMS:4:2:4+0020::Informationen fehlerfrei entgegengenommen.+3050::BPD nicht mehr aktuell. Aktuelle Version folgt.+3920::Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer:900'HIRMS:5:2:5+0020::Die Synchronisierung der Kundensystem-ID war erfolgreich.'HIBPA:6:2:4+7+280:50010517+ING-DiBa+0+1+220:300+200'HIKOM:7:3:4+280:50010517+1+3:https?://fints.ing-diba.de/fints/'HISPAS:8:1:4+1+1+0+J:J:J:urn?:iso?:std?:iso?:20022?:tech?:xsd?:pain.001.003.03'HIPAES:9:1:4+1+1+0'HICCSS:10:1:4+1+1+0'HITANS:11:1:4+1+1+0+J:N:0:0:900:2:iTAN:iTAN:6:1:Index:3:1:N:N'HIKAZS:12:5:4+1+1+390:N:N'HICDNS:13:1:4+1+1+1+0:1:360:J:J:J:J:J:N:N:N:J:00:00::0'HICSBS:14:1:4+1+1+0+N:N'HICSAS:15:1:4+1+1+0+1:360'HIWPDS:16:6:4+1+1+0+N:N:N'HIWPDS:17:5:4+1+1+N:N:N'DIPAES:18:1:4+1+1'HICDLS:19:1:4+1+1+1+1:360:N:J'HIPROS:20:3:4+1+1'HICSES:21:1:4+1+1+0+1:360'HICSLS:22:1:4+1+1+0+J'HICDBS:23:1:4+1+1+0+N'HISALS:24:5:4+1+1'HICDES:25:1:4+1+1+1+4:1:360:00:00::0'DIPINS:26:1:4+1+1+HKSPA:N:HKPAE:J:HKCCS:J:HKTAN:N:HKKAZ:N:HKCDN:J:HKCSB:N:HKCSA:J:HKWPD:N:DKPAE:J:HKCDL:J:HKPRO:N:HKCSE:J:HKCSL:J:HKCDB:N:HKSAL:N:HKCDE:J'HIPINS:27:1:4+1+1+0+5:10:6:Kontonummer::HKSPA:N:HKPAE:J:HKCCS:J:HKTAN:N:HKKAZ:N:HKCDN:J:HKCSB:N:HKCSA:J:HKWPD:N:DKPAE:J:HKCDL:J:HKPRO:N:HKCSE:J:HKCSL:J:HKCDB:N:HKSAL:N:HKCDE:J'HISYN:28:3:5+000006GOR2T4D4VOCV9LOK35FFF5EJ'HNHBS:29:1+1'
  Lese empfangene Antwortnachricht (SynchRes))
  Überprüfe Signatur der Antwortnachricht
<WRN> [2021.04.28 16:18:48.272] [main/main] security.Sig: message has no signature
kreditinstituts-spezifische Daten erhalten - neue Version ist 7
neue System-ID erhalten - neue System-ID ist 000006GOR2T4D4VOCV9LOK35FFF5EJ
status: 3060:Teilweise liegen Warnungen/Hinweise vor.
3050:BPD nicht mehr aktuell. Aktuelle Version folgt. (4: Synch.ProcPrep)
3920:Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer p:900 (4: Synch.ProcPrep)
0020:Angemeldet. (3: Synch.Idn)
0020:Informationen fehlerfrei entgegengenommen. (4: Synch.ProcPrep)
0020:Die Synchronisierung der Kundensystem-ID war erfolgreich. (5: Synch.Sync)
  Erzeuge HBCI-Nachricht DialogEnd
  signiere HBCI-Nachricht
  Verschlüssele HBCI-Nachricht
<WRN> [2021.04.28 16:18:48.303] [main/main] protocol.MSG: could not insert the following user-defined data into message: Crypted.CryptHead.SecProfile.method=PIN
<WRN> [2021.04.28 16:18:48.303] [main/main] protocol.MSG: could not insert the following user-defined data into message: Crypted.CryptHead.SecProfile.version=2
  Versende HBCI-Nachricht
Sende HBCI-Nachricht: HNHBK:1:3+000000000416+220+000006GOR2SVL38T4NJBB70723MNHI+2'HNVSK:998:2+998+1+1::000006GOR2T4D4VOCV9LOK35FFF5EJ+1:20210428:161848+2:2:13:@8@        :5:1+280:50010517:xxxxxxxxxx:V:0:0+0'HNVSD:999:1+@201@HNSHK:2:3+900+991989140+1+1+1::000006GOR2T4D4VOCV9LOK35FFF5EJ+1+1:20210428:161848+1:999:1+6:10:16+280:50010517:xxxxxxxxxx:S:0:0'HKEND:3:1+000006GOR2SVL38T4NJBB70723MNHI'HNSHA:4:1+991989140++xxxxxxxxxx''HNHBS:5:1+2'
  Warte auf Antwortdaten
HBCI-Nachricht empfangen: HNHBK:1:3+000000000247+220+000006GOR2SVL38T4NJBB70723MNHI+9999+000006GOR2SVL38T4NJBB70723MNHI:9999'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9400::Der Wechsel des Sicherheitsverfahrens während eines Dialoges ist nicht erlaubt.'HNHBS:3:1+9999'
  Lese empfangene Antwortnachricht (CryptedRes))
  Lese empfangene Antwortnachricht (DialogEndRes))
HBCI-Nachricht empfangen und entschlüsselt: HNHBK:1:3+000000000247+220+000006GOR2SVL38T4NJBB70723MNHI+9999+000006GOR2SVL38T4NJBB70723MNHI:9999'HIRMG:2:2+9800::Der Dialog wurde abgebrochen.+9400::Der Wechsel des Sicherheitsverfahrens während eines Dialoges ist nicht erlaubt.'HNHBS:3:1+9999'
<ERR> [2021.04.28 16:18:48.471] [main/main] status.HBCIStatus: Meldung der Bank: 9800:Der Dialog wurde abgebrochen.
<ERR> [2021.04.28 16:18:48.472] [main/main] status.HBCIStatus: Meldung der Bank: 9400:Der Wechsel des Sicherheitsverfahrens während eines Dialoges ist nicht erlaubt.
<ERR> [2021.04.28 16:18:48.473] [main/main] manager.HBCIUtils: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:428)
	at org.kapott.hbci.manager.HBCIKernelImpl.rawDoIt(HBCIKernelImpl.java:176)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.sendData(AbstractRawHBCIDialog.java:123)
	at org.kapott.hbci.dialog.HBCIDialogEnd.sendData(HBCIDialogEnd.java:95)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:96)
	at org.kapott.hbci.manager.HBCIUser.fetchSysId(HBCIUser.java:454)
	at org.kapott.hbci.manager.HBCIUser.sync(HBCIUser.java:656)
	at org.kapott.hbci.manager.HBCIUser.register(HBCIUser.java:704)
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:167)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	at io.levitin.hbci.Diba.main(Diba.java:42)
Dialog beendet
status: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
9800:Der Dialog wurde abgebrochen.
9400:Der Wechsel des Sicherheitsverfahrens während eines Dialoges ist nicht erlaubt.
<ERR> [2021.04.28 16:18:48.474] [main/main] dialog.HBCIDialogEnd: dialog end failed: org.kapott.hbci.exceptions.HBCI_Exception: empfangene Nachrichtennummer (9999) im Nachrichtenkopf entspricht nicht der gesendeten Nachrichtennummer (2)
9800:Der Dialog wurde abgebrochen.
9400:Der Wechsel des Sicherheitsverfahrens während eines Dialoges ist nicht erlaubt.
<ERR> [2021.04.28 16:18:48.475] [main/main] manager.HBCIUtils: org.kapott.hbci.exceptions.ProcessException: Dialog-Ende fehlgeschlagen
	at org.kapott.hbci.dialog.HBCIDialogEnd.checkResult(HBCIDialogEnd.java:124)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:106)
	at org.kapott.hbci.manager.HBCIUser.fetchSysId(HBCIUser.java:454)
	at org.kapott.hbci.manager.HBCIUser.sync(HBCIUser.java:656)
	at org.kapott.hbci.manager.HBCIUser.register(HBCIUser.java:704)
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:167)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	at io.levitin.hbci.Diba.main(Diba.java:42)
Callback für Passport mit Init-Daten: null
Sie können die Internetverbindung jetzt beenden
<ENTER> drücken, um fortzufahren

Exception in thread "main" org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Erzeugen eines HBCIHandler Objektes
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:141)
	at io.levitin.hbci.Diba.main(Diba.java:42)
Caused by: org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Registrieren der Nutzerdaten
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:169)
	at org.kapott.hbci.manager.HBCIHandler.<init>(HBCIHandler.java:132)
	... 1 more
Caused by: org.kapott.hbci.exceptions.HBCI_Exception: Fehler beim Ermitteln einer neuen System-ID
	at org.kapott.hbci.manager.HBCIUser.fetchSysId(HBCIUser.java:462)
	at org.kapott.hbci.manager.HBCIUser.sync(HBCIUser.java:656)
	at org.kapott.hbci.manager.HBCIUser.register(HBCIUser.java:704)
	at org.kapott.hbci.manager.HBCIHandler.registerUser(HBCIHandler.java:167)
	... 2 more
Caused by: org.kapott.hbci.exceptions.ProcessException: Dialog-Ende fehlgeschlagen
	at org.kapott.hbci.dialog.HBCIDialogEnd.checkResult(HBCIDialogEnd.java:124)
	at org.kapott.hbci.dialog.AbstractRawHBCIDialog.execute(AbstractRawHBCIDialog.java:106)
	at org.kapott.hbci.manager.HBCIUser.fetchSysId(HBCIUser.java:454)
	... 5 more

Process finished with exit code 1
</details>

The same code works fine for two other banks, but not more for ING. 
The interesting thing is, in [Hibiscus ](https://github.com/willuhn/hibiscus) my data can still be accessed, although I see similar errors for ING in Hibiscus logs.

And yes, I tried connection with differenz HBCI Versions. Does anyone know a workaround for ING, with which one can get account data?

**Comment by willuhn** [comment]
Sorry. Die ING kann kein PSD2 per FinTS/HBCI. Das Problem ist nicht HBCI4Java sondern die Bank. Im Wiki unter https://www.willuhn.de/wiki/doku.php?id=psd2#ing findest du ausführlichere Informationen zu dem Thema.

**Comment by levitin** [comment]
Ok, I found a workaround now. One should use the last 3.0.x version, just like in old times, nevertheless with HBCI 3.0.
