### ISSUE TITLE
Customer's IBAN is being cut off at 27 characters

### ISSUE THREAD

**Issue by iain-bitcoin** [hbci4j/hbci4java#57]
We have seen a few examples of customer IBAN's being cut off at 27 characters. We can see the data is correct at 28 characters in our account but when it comes to our system through this library it is only 27. Are there any limitations which would cause this? We are getting the field from GVRKUms.UmsLine.other.number

**Comment by willuhn** [comment]
Das Datenformat Swift MT940, in dem du die Umsätze abrfust, ist auf 27 Zeichen pro Zeile im Verwendungszweck codiert. Da die Bank die IBAN im Verwendungszweck überträgt, wird auch die nach 27 Zeichen abgeschnitten. Das passiert also nicht durch HBCI4Java sondern durch die Bank.

Verwende für den Umsatzabruf den neuen SEPA-tauglichen per CAMT "KUmsZeitCamt". Dort existieren diese Einschränkungen nicht mehr.
