### ISSUE TITLE
Eigenen Java Security Provider in Passport vorgeben

### ISSUE THREAD

**Issue by machajdik** [hbci4j/hbci4java#6]
Hallo,
für meine Anwendung muss ich den [Provider](https://docs.oracle.com/javase/8/docs/api/java/security/Provider.html) für die HBCI-Aufrufe explizit setzen.
Das betrifft die Klassen AbstractHBCIPassport sowie alle HBCIPassport* Klassen (Aufrufe SecretKeyFactory.getInstance() und Cipher.getInstance()).
Meint ihr, dass dies auch für andere sinnvoll ist? Dann würde ich einen Pull Request zur Verfügung stellen. Die Auswahl des Providers würde dann über eine Property erfolgen. Natürlich wäre das ganze rückwärtskompatibel.
lg
Manuel

**Comment by willuhn** [comment]
Was ich nicht ganz verstehe: Warum musst du den Provider explizit an der Stelle setzen? Man kann den doch einfach global fuer die ganze JVM-Instanz im eigenen Code definieren:

> Provider p = new BouncyCastleProvider();
> Security.insertProviderAt(p,0); // Vorn in die Liste einfuegen

Dann sollte der als Default-Provider verwendet werden.

**Comment by machajdik** [comment]
Hi, leider brauche an verschiedenen Stellen meiner Anwendung verschiedene Provider (zB für HBCI den SunJCE, für HTTP Requests BouncyCastle, etc.) - daher muss ich den immer explizit setzen...

**Comment by willuhn** [comment]
Ich selbst wuerde das Feature nicht brauchen - aber vielleicht andere User. Und wenn's abwaertskompatibel ist: Mach 'nen Pull-Request.

PS: BouncyCastle kann doch eigentlich alles, was auch SunJCE kann. Koenntest du da nicht auch den HBCI-Teil ueber BouncyCastle laufen lassen?
