### ISSUE TITLE
Proxy Einstellungen ignoriert

### ISSUE THREAD

**Issue by markokocic** [hbci4j/hbci4java#7]
Verbindung mit Schlusseldiskette-Metode funktioniert nicht wenn Computer hinter dem Proxy server ist.
Proxy Einstellungen in Hibiscus sind einfach ignoriert.

**Comment by willuhn** [comment]
Das ist korrekt. Beim Verfahren Schluesseldatei und Chipkarte wird NICHT das HTTP-Protokoll als Transport verwendet sondern es werden die HBCI-Nachrichten direkt auf dem "rohen" TCP-Socket zum Server (TCP-Port 3000) gesendet. Dieses Protokoll kann daher nicht in Verbindung mit einem HTTP-Proxy verwendet werden.

Eventuell koenntest du die JVM-System-Properties "socksProxyHost" bzw. "socksProxyPort" wie in https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html - Absatz 2.4 beschrieben, mal ausprobieren. Ich weiss aber nicht, ob das funktioniert. Dafuer brauchst du dann aber auch einen speziellen Proxy, der SOCKS beherrscht.

**Comment by markokocic** [comment]
Ja, ich habe es jetzt probiert, und es funktioniert mit `-DsockProxyHost` und` -DsocksProxyPort` Parametern. Das einzige Problem jetzt ist, dass im Hibiscus Proxyeinstellungen keine SocksProxy Optionen gibt.

**Comment by willuhn** [comment]
Die Optionen brauchst du zum reinen Test auch nicht in Hibiscus. Es reicht, wenn du in der jameica.sh dieses System-Properties mit angibst. Wenn es dennoch nicht funktioniert, dann kann dein Proxy entweder kein SOCKS oder es laesst sich tatsaechlich per SOCKS-Proxy transportieren. Das kann ich nicht beurteilen - ich kenne mich mit SOCKS leider nicht aus.

**Comment by markokocic** [comment]
Als gesagt, ich habe schon getestes, and es funktioniert ganz gut, wenn ich diese socks parameters als -D Parameters abgebe.

Die Frage ist eher, können wir diese Option in Hibiscus ProxyEinstellungen UI haben? Das wäre Hibiscus Ticket, auf hbci4java Seite alles jetzt funktioniert.

**Comment by willuhn** [comment]
> Als gesagt, ich habe schon getestet, und es funktioniert ganz gut, wenn ich diese
> socks Parameters als -D JVM Parameters abgebe.

Ah, da hatte ich dein Posting vorhin falsch verstanden. Hatte gedacht, dass es NICHT funktioniert. OK, schoen, dass es ja doch funktioniert hat.

> Die Frage ist eher, können wir diese Option in Hibiscus ProxyEinstellungen UI haben?
> Das wäre Hibiscus Ticket, auf hbci4java Seite alles jetzt funktioniert.

Du bist in 13 Jahren Hibiscus-Geschichte der erste mir bekannte User, der das benötigt. Es betrifft also extrem wenige User. Ich halte es daher nicht für sinnvoll, das als Option in die Proxy-Einstellungen in der Jameica-UI mit einzubauen. Die Anzahl der User, die das benötigen ist einfach viel zu klein.
