### ISSUE TITLE
IBAN geht beim Parsen von KInfo6 verloren

### ISSUE THREAD

**Issue by mwalliczek** [hbci4j/hbci4java#70]
Beim Parsen von KInfo6 innerhalb von hbci-300.xml wird die iban direkt als Kindelement in die KInfo geschrieben.
Sie wird im weiteren Programmablauf aber innerhalb des KTV-Blocks im KInfo erwartet, wie bei KInfo5, siehe z.B. AbstractHBCIPassport:249 entry.iban=upd.getProperty(header+".KTV.iban");

Insofern führt das Parsen von KInfo6 dazu, dass die iban an der falschen Stelle steht und damit nicht erkannt wird.

**Comment by willuhn** [comment]
Ich verstehe das Problem gerade nicht. Welches Parsen meinst du? KInfo6 definiert ein DEG vom Typ KTV, in dem die IBAN von der Bank geliefert wird. Von dort wird sie dann auch wieder gelesen. Habe gerade bei meinem SPK-Konto nachgeschaut. Die IBAN steht in KInfo6.KTV.iban.

**Comment by mwalliczek** [comment]
Unterhalb des KTV gibt es (nur) bei KInfo6 noch ein separates iban Feld, das bei mir bei der Consorsbank gefüllt wird. In diesem Fall verschwindet die IBAN, außer ich lese sie per SEPAInfo extra aus.

**Comment by willuhn** [comment]
Das iban-Feld in dem KTV wird auch bei meiner Sparkasse gefüllt. Und per "upd.getProperty(header+".KTV.iban")" auch wieder von dort gelesen. Sorry, ich verstehe das Problem nicht. Kannst du vielleicht einen PR erstellen? Ich weiss nicht, was ich hier fixen soll.

**Comment by mwalliczek** [comment]
Also Fakt ist, dass ich bei der Consorsbank (und nur dort) regelmäßig das Problem habe, dass die IBAN aus dem Konto verschwindet; und im UPD nur noch per KInfo.iban (ohne .KTV.) gespeichert ist.

Hier der HIUPD-Abschnitt aus der Response:
`'HIUPD:31:6:4+<KontoNr>::280:<BLZ>+<IBAN>+XXXXXXXXXXXXX++EUR+<KontoInhaber>++Lohn/Gehalt/Rente Privat++HKCCS:1+HKKAZ:1+HKSPA:1+HKSAL:1+HKPRO:1`

Ich muss dann den IBAN komplett löschen und neu per SEPAInfo abrufen. Mein Verdacht war, dass es mit der Besonderheit im KInfo6 zusammenhängt, und der Tatsache, dass die iban dort einmal innerhalb des KTV und einmal direkt vorkommt. Trotz längerer Suche habe ich aber keine weitere Idee, woran das sonst liegen könnte und wie man das fixen könnte.

**Comment by willuhn** [comment]
Dann liefert die Consorsbank die IBAN wahrscheinlich nur direkt in KInfo6.iban, nicht aber in KInfo6.KTV.iban.
Beim Aufruf von SEPAInfo (den GV gibts leider doppelt - einmal in GVSEPAInfo, Zeile 106 und einmal in HBCIDialogSepaInfo, Zeile 152) versucht HBCI4Java eine ggf. in Kinfo.KTV.iban fehlende IBAN wieder basierend auf den Daten aus SEPAInfo zu vervollständigen. Wenn dann aber irgendwann wieder ein neuer UPD-Abruf kommt, verschwindet die IBAN wieder von dort, wenn die Bank in Kinfo.KTV.iban nichts liefert, dafür aber zumindest in KInfo.iban.

Das ist aber nur eine Vermutung. Das Problem müsste immer dann auftreten, wenn eine Bank die IBAN zwar per SEPAInfo liefert, nicht aber in den UPD per Kinfo.KTV.iban

Als Workaround könnte hier in AbstractHBCIPassport, Zeile 249 folgendes helfen:

``
entry.iban=upd.getProperty(header+".KTV.iban");
if (!StringUtils.hasText(entry.iban))
  entry.iban=upd.getProperty(header+".iban");
````

Da ich kein betroffenes Konto habe. Kannst du das mal bei dir testen?

**Comment by mwalliczek** [comment]
Das hilft leider nicht, dann fehlt mir die BIC... Das Problem liegt ganz wo anders: Der Mechanismus in HBCIUser Zeile 564, der die fehlenden IBAN und BIC retten soll, basiert darauf, das die Konten immer in der gleichen Reihenfolge gesendet werden. Die Consorsbank liebt aber etwas Abwechslung und so werden innerhalb einer Session die Konten in verschiedener Reihenfolge gesendet, und wenn dann KInfo_2 aus der udp dem KInfo_4 aus dem result entspricht, dann funktioniert das alles nicht.
Ich werde einen PR erstellen, der da etwas toleranter ist.

**Comment by mwalliczek** [comment]
Siehe https://github.com/hbci4j/hbci4java/pull/72
