### ISSUE TITLE
Detach fork

### ISSUE THREAD

**Issue by madmuffin1** [hbci4j/hbci4java#71]
Hallo zusammen,

da das Repo hbci4j/hbci4java geforked ist, findet man es leider nicht über die GitHub Suche und auch Google indiziert es nicht. Auch Code-Search etc. funktioniert nur eingeschränkt.

Der Owner des Repos kann unter https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks%2Cfork den Fork "detachen", so kann der Flag entfernt werden und die o.g. Einschränkungen sollten sich auflösen.

Grüße!

**Comment by willuhn** [comment]
Danke für den Hinweis. Ich bin über die Seite https://support.github.com/request/fork gegangen und dann ebenfalls dort gelandet. Google findet zu dem Thema kaum etwas - wirklich gut ist das ja nicht dokumentiert. Habe es nur darüber gefunden: https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

Detach ist gestartet.
