### ISSUE TITLE
cryptalgs ist noch GPL 2.0+

### ISSUE THREAD

**Issue by Mailaender** [hbci4j/hbci4java#8]
Siehe Kopfzeile von https://github.com/hbci4j/hbci4java/tree/master/src/main/java/org/kapott/cryptalgs und https://github.com/willuhn/hbci4java/issues/36 ist 404.

**Comment by willuhn** [comment]
Wir haben doch alle Autoren, die Code begesteuert haben, befragt und gemeinsam die Aenderung beschlossen.  Sicher finden sich hier und da noch Hinweise in den Quellcode-Dateien, in denen der Lizenztext noch nicht aktualisiert ist. Ich habe aber ehrlich gesagt keine Muse, mich durch jede einuelne Datei zu wuehlen und die Kommentare ueberall zu aktualisieren. Ich mache das immer dann, wenn ich ohnehin gerade an einer der Dateien arbeite.
Wenn dich die Kommentare stoeren, kannst du sie gern aendern und es als Pull-Request einreichen.

**Comment by Mailaender** [comment]
Ich erinnere mich auch noch, dass es diesen Beschluss gab. Nur ist der Link tot. Für Außenstehende ist es aber nicht nachvollziehbar. Das Projekt würde daher durch ein "legal review" rasseln.

**Comment by willuhn** [comment]
Der Link ist leider tot, weil ich die Issues-Sektiom in dem alten Repository zugemacht habe, damit dort keiner mehr Tickets aufmacht. Es gab leider keine Moeglichkeit, es auf Read-Only zu setzen. Unter https://github.com/hbci4j/hbci4java steht ja aber die Info zur Lizenz. Ich kann mir nicht vorstellen, dass es bei einem Review noetig ist, historisch zu belegen, unter welchen Umstaenden es zur Findung der Lizenz kam. Bei Hibiscus hat mich auch noch keiner gebeten, darzulegen, wie ich damals zu dem Entschluss gekommen bin.

Und wie gesagt, wenn die restlichen noch falschen Kommentare im Quellcode stoeren, kannst du es gern aendern.
