### ISSUE TITLE
"Duplicate property key" in blz.properties: 75062026

### ISSUE THREAD

**Issue by mtotschnig** [hbci4j/hbci4java#84]
Beim Öffnen der Datei in Android Studio fällt auf, dass der Eintrag für BLZ 75062026 (Raiffeisenbank Oberpfalz Süd) doppelt vorkommt.
Das scheint zwar beim Ablauf des Programms nicht problematisch, deutet aber vielleicht auf ein Fehler beim Generieren der Datei hin?
Wie wird die Datei eigentlich generiert? Sie enthält 4054 Einträge, in der Datei, die von registrierung@hbci-zka.de verschickt wird, sehe ich aber nur 1851 unterschiedliche Bankleitzahlen.

**Comment by willuhn** [comment]
Danke für den Hinweis mit dem Duplikat. Den Eintrag hatte ich mit https://github.com/hbci4j/hbci4java/commit/f04caccfed57a47a3a83f18d40a4a6148761ede5 versehentlich angelegt. Da kam ein Update vom ZKA. Hatte offensichtlich nicht bemerkt, dass die Bank bereits enthalten ist und sie manuell hinzugefügt. Habe ihn wieder entfernt.

Zu der Gesamtanzahl der Einträge: Die Liste vom ZKA ist nicht vollständig - soweit ich weiss, enthält sie nur Banken, die im ZKA sind. Wie die Liste in HBCI4Java zu dieser Größe kam, kann ich leider nicht sagen. Sie stammt ursprünglich von Stefan Palme's HCBI4Java (https://sourceforge.net/projects/hbci4java/). Eine vollständige Liste aller BLZ findest du in https://github.com/willuhn/obantoo/blob/main/src/BLZ.txt (das ist die offizielle Liste von der Bundesbank).
