### ISSUE TITLE
Client Pain Version

### ISSUE THREAD

**Issue by JohannMaierhofer** [hbci4j/hbci4java#85]
Beim Generieren von Lastschriften in openjverein wird über einen Dialog, der von Hibiscus implementiert ist, der User zur Auswahl der SEPA XML Version (Pain 008) aufgefordert.
Der Dialog bietet alle 008 Versionen an. 8.001.10 wird als greatest geliefert und per Default angezeigt. Als unbedarfter User klickt man wahrscheinlich gleich weiter und nimmt an, dass der Default schon passen wird. 
Ich habe gelesen, dass 8.001.10 das Format für die Antwort des Servers zum Client ist. Das neueste Format für den Client Request zum Server ist die 8.001.08.
Jverein sollte also die 8.001.10 gar nicht anbieten. Nun könnte man das in openjverein abfangen.
Wäre es nicht sinnvoll in SepaVersion.java Methoden einzubauen welche entweder nur Client Versionen zurückgeben oder Filter Methoden die aus einer Liste die Client Versionen herausfiltern.
Oder anders gefragt, wenn hbci4java evtl. sowieso nur für Clients gedacht ist, könnte man die Versionen für Server ganz weglassen.

**Comment by willuhn** [comment]
Hast du eine Quelle, wo steht, dass. 10 nicht für Clients zulässig ist?

**Comment by JohannMaierhofer** [comment]
Ich habe das in der Anlage_3_Datenformate_3.7.pdf Kapitel 2 gefunden welche ich von dieser Seite https://www.ebics.de/de/Datenformate herunterladen habe.

**Comment by JohannMaierhofer** [comment]
Jetzt muss ich mich korrigieren. Ich habe nicht genau hingeschaut. Bei der Antwort des Server ist es 2.001.10 und nicht die 8.001.10.
Wo dann 8.001.10 verwendet wird versuche ich noch rauszubekommen.

**Comment by willuhn** [comment]
Kann es vielleicht sein, dass das Problem gar nicht existiert und 8.001.10 verwendet werden kann?

**Comment by JohannMaierhofer** [comment]
Ich hab noch dieses Dokument (https://www.ebics.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTk3OTAzODMsImV4cCI6MTY5OTg4MDM4MiwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW5cL3Vuc2VjdXJlZFwvYW5sYWdlM1wvYW5sYWdlM19TRVBBTGlmZUN5Y2xlXC9TRVBBLUxpZmVDeWNsZUZvcm1hdHZlcnNpb25lbi1TdGFuZE9rdG9iZXJfMjAyMy5wZGYiLCJwYWdlIjoxMjZ9.LMkoFUaC7ptBmVOSZIyny_qeB1gUcbacYVD-YolPSxU/SEPA-LifeCycleFormatversionen-StandOktober_2023.pdf) von https://www.ebics.de/de/datenformate/format-lifecycle herunter geladen. 
Es scheint kein 8.001.10 zu geben.

**Comment by willuhn** [comment]
Aber ich habe mir die Versionen doch nicht ausgedacht sondern die zugehörigen XML-Schema-Dateien (liegen in src/main/resources) direkt von ebics.de heruntergeladen.

**Comment by willuhn** [comment]
Gerade nochmal nachgeschaut. Hier ist die Version 008.001.10:
https://www.iso20022.org/iso-20022-message-definitions?business-domain%5B0%5D=1&search=pain.008

Das ist auch die Quelle für die PAIN-Messages. Unter https://www.ebics.de/de/datenformate findet sich ein Hinweis "...Auf Ebene des für die Standardisierung des SEPA-Zahlungsverkehrs zuständigen European Payments Council wurde am 24.10.2023 eine Verschiebung der zum 19.11.2023 geplanten Formatmigration (von ISO-Version 2009 auf ISO-Version 2019) im SEPA-Zahlungsverkehr auf den 17.03.2024 beschlossen....". Möglicherweise steht das damit im Zusammenhang. Laut der dort verlinkten "3.7 der Anlage 3 des DFÜ-Abkommens" ist die letzte Version in der Tat 008.001.10.

Das Commit in HBCI4Java stammt von @ruderphilipp - https://github.com/hbci4j/hbci4java/pull/59
@ruderphilipp Kannst du sagen, wo du die XML-Schema-Dateien her hast? Im Rahmen von FinTS gelten die unter https://www.ebics.de/de/datenformate genannten Versionen.

**Comment by willuhn** [comment]
@JohannMaierhofer Was mich in dem Zusammenhang interessiert: Wie kam es zu dem Issue hier? Hattest du eine PAIN-Datei erzeugt, die anschließend von der Bank abgelehnt wurde? Denn: Diese PAIN-Version 008.001.10 ist ja schon seit ca. 1,5 in HBCI4Java und damit auch in Hibiscus enthalten. Und seither haben sicher schon viele User PAIN-Dateien mit dieser Version erstellt und bei der Bank eingereicht. Bisher hat aber noch keiner von einem Problem in dem Zusammenhang berichtet.

**Comment by JohannMaierhofer** [comment]
Ich habe keine Datei erzeugt. Mir ist nur die etwas seltsame Sortierung im Menü aufgefallen. Also die 8.001.xx nach 8.003.xx. Um das zu verstehen und nicht gleich eine Fehlermeldung zu schreiben habe ich nach der Ursache gesucht und die oben genannten Dokumente gefunden.
Scheinbar gibt es dann eine 008.001.10 von der ISO. Sie wird aber wohl dann zumindest (noch) nicht offiziell beim SEPA benutzt.
Unschön ist natürlich, dass diese Version als Default in openjverein auftaucht. 
Man könnte jetzt eine Methode getLatestSepaVersion einführen die dann bei Lastschriften die 8.001.02 liefert und ab 17.03.2024 dann die 008.001.08. Das könnte man statt greatest als Default nehmen.
Einfacher wäre es sicherlich in openjverein statt dem greatest einfach fix die 008.001.02 als Default zu nehmen. Das ist sowieso die einzige momentan offiziell gültige Version und würde auch die Abhängigkeit von einer zukünftigen Hibiscus Version vermeiden.

**Comment by willuhn** [comment]
Dass die Versionsnummern nicht der Reihenfolge entsprechen, ist leider Tatsache. Den Sinn hatte ich auch nicht verstanden, genau dafür aber eine separate Sortierfunktion in HBCI4Java einbauen müssen. Die derzeit aktuelle Version ist aber 008.001.08 und nicht 008.001.02

**Comment by willuhn** [comment]
PS: Wenn kein Fall bekannt ist, bei dem eine Bank eine 008.001.10 tatsächlich abgelehnt hat, bin ich mir nicht sicher, ob sich die ganze Diskussion hier überhaupt lohnt. Wozu etwas ändern, wenn gar kein konkretes Problem aufgetreten ist?

**Comment by JohannMaierhofer** [comment]
Ja, du kannst den Issue schließen.
P. S. Hätte ich diese Diskussion in einem Forum führen sollen anstatt über ein Issue?

**Comment by willuhn** [comment]
> Ja, du kannst den Issue schließen.

Ich warte mal noch auf die Antwort von Philipp. Er hatte den PR mit der Version eingereicht. Würde gern wissen, woher die Schema-Datei stammt. 

> P. S. Hätte ich diese Diskussion in einem Forum führen sollen anstatt über ein Issue? 

Für so technische Themen finde ich die Issues hier schon richtig.

**Comment by willuhn** [comment]
Leider keine Antwort von Philipp. Ich schliesse das Issue mal. Falls sich ein User meldet, der tatsächlich Probleme mit der erzeugten PAIN-008.001.10-Datei hatte (z.B. weil die Bank sie nicht akzeptiert oder sie sich in einem anderen Programm nicht einlesen ließ), dann entferne ich die Version aus der Auswahlliste.

**Comment by ruderphilipp** [comment]
Hallo,
bitte entschuldigt die verspätete Rückmeldung. Ich war auf Dienstreise.

Wie in https://github.com/hbci4j/hbci4java/blob/master/pom.xml#L204 dokumentiert, hatte ich die Dateien von www.iso20022.org geholt. 

Laut https://github.com/hbci4j/hbci4java/blob/master/pom.xml#L216 ist wohl `008.001.08` die aktuell gültige Version für SEPA...

**Comment by willuhn** [comment]
Prima. Danke für die Rückmeldung. Ich lass die Version erstmal drin, da sich bisher noch keiner gemeldet hat, der wirklich einen Fehler mit 008.001.10 hatte.
