### ISSUE TITLE
ant build Error: Could not find class file for 'org.kapott.hbci.passport.HBCIPassportDDV'.

### ISSUE THREAD

**Issue by Mailaender** [hbci4j/hbci4java#9]
```
[    3s] + cd hbci4java-hbci4j-core-3.0.10
[    3s] + JAVA_HOME=/usr/lib64/jvm/java
[    3s] + ant
[    3s] Buildfile: /home/abuild/rpmbuild/BUILD/hbci4java-hbci4j-core-3.0.10/build.xml
[    3s] 
[    3s] compile:
[    4s]     [javah] Error: Could not find class file for 'org.kapott.hbci.passport.HBCIPassportDDV'.
[    4s] 
[    4s] BUILD FAILED
[    4s] /home/abuild/rpmbuild/BUILD/hbci4java-hbci4j-core-3.0.10/build.xml:11: compilation failed
```

:disappointed: 

Leider funktioniert `mvn` nicht unter build.opensuse.org so dass ich auf das `build.xml` angewiesen bin. Lässt es sich wieder restaurieren?

**Comment by willuhn** [comment]
Ich weiss ja nicht, wie die Buld-Umgebung bei dir auf dem Suse-Server aussieht. Von daher kann ich dir da auch nicht wirklich helfen sondern hoechstens Mutmaßungen anstellen. Vielleicht hast du nicht den kompletten Code ausgecheckt. Bei mir geht der Build jedenfalls mit Maven - ich baue die Releases jetzt schom seit einiger Zeit damit.

**Comment by Mailaender** [comment]
Das Problem ist, dass Maven Abhängigkeiten aus dem Internet zieht und noch keine offline Lösung wie `xmvn` unter SUSE existiert, da es Probleme mit dem bootstrapping gibt. Daher weiche ich auf `ant` aus und das klappt leider nicht mehr `BUILD FAILED`. Sind vielleicht die Umstrukturierungen der `build.xml` daran Schuld? https://github.com/willuhn/hbci4java/blob/master/build.xml war noch deutlich ausführlicher.

**Comment by willuhn** [comment]
Es tut mir leid, dass das Build da auf deinem System jetzt nicht klappt. Aber was soll ich denn daran jetzt aendern? Es ist ja auch nicht mehr wirklich sinnvoll, hier jetzt zwei Build-Tools parallel zu pflegen.

**Comment by asbachb** [comment]
@Mailaender , was willst du denn eigentlich erreichen? hcbi4java bzw. hibiscus für opensuse packagen?! Wird doch nicht die erste Java-Applikation sein, die maven nutzt...?!

**Comment by asbachb** [comment]
Schau mal hier: https://build.opensuse.org/package/show/home:uwemock/jes , da werden einfach die Binaries gezogen.

**Comment by Mailaender** [comment]
Mein https://build.opensuse.org/package/show/home:Mailaender:branches:Java:packages/hbci4java kann ich dadurch nicht mehr aktualisieren. Ein kleiner Rückschritt für mein Hibiscus Paket, da die Kernkomponenten jetzt nicht mehr aus dem Quelltext gebaut werden kann. Mittlerweile passen die Jameica und Hibiscus releases wieder zusammen: https://build.opensuse.org/request/show/514813 und ich kann aktualisieren.

Es ist tatsächlich traurig, dass Java-Paketierung unter @openSUSE so umständlich ist und Maven überhaupt nicht unterstützt wird. Unter https://build.opensuse.org/project/show/Java:maven gibt es erste Experimente. Ich habe es bislang nicht geschafft damit etwas hinzubekommen.

Einfach die binaries zu kopieren ist die einfachste Variante und eigentlich nicht erlaubt ("build" service). Ich hatte schon daran gedacht Hibiscus bei @FlatHub mit @FlatPak zu paketieren, wo das herunterladen von fertig gebauten Artefakten grundsätzlich möglich ist, damit proprietäre Software unterstützt werden kann.

**Comment by willuhn** [comment]
Ich muss halt Interessen abwaegen. Und eine deutliche Mehrheit der hbci4java-Nutzer wuenschte sich halt, dass die Releases per Maven-Repo verfuegbar sind, damit sie in anderen Java-Anwendungen bequem per Dependency-Management in Maven oder Gradle eingebunden werden koennen.
