### ISSUE TITLE
String bei callback `NEED_PT_TANMEDIA` ist seit 3.1.80 leer (Sparkasse)

### ISSUE THREAD

**Issue by guyyst** [hbci4j/hbci4java#92]
Auf Version `3.1.79` bekomme ich für meine Sparkasse bei dem callback `NEED_PT_TANMEDIA` in `retData` den String `Alle Geräte`. Auf `3.1.80` ist der String leer. Wenn ich auf dieser Version einfach in `retData` manuell wieder `Alle Geräte` reinschreibe, und das callback returne, klappt der restliche Prozess wie immer.

Basierend auf den Commits zwischen `.79` und `.80` nehme ich mal an es liegt an dem neuen default Wert von `INIT_FLIP_USER_INST` aus dieser Änderung: https://github.com/hbci4j/hbci4java/commit/257a5500c1a3a0f4afc83e54c392d001086c47e3

Ist das eher ein Problem mit meiner Sparkasse? (Hab es nur mit einer testen können)

**Comment by willuhn** [comment]
Ich kann das Verhalten bei meiner Sparkasse nicht reproduzieren. Wenn ich einen Bankzugang neu anlege und synchronisiere, erhalte ich initial genau diese TAN-Medienbezeichnung "Alle Geräte". Das Feature INIT_FLIP_USER_INST ist sogar eben genau dafür eingebaut worden - um die TAN-Medien direkt am Anfang schon zu erhalten, indem initial kein anonymer Dialog zum Abruf der BPD mehr gemacht wird sondern direkt eine authentifizierter Dialog zum Abruf der UPD. Hier der zugehörige PR: https://github.com/hbci4j/hbci4java/pull/67

Und wie gesagt - ich habe es gerade eben mit meinem Sparkassenkonto getestet und sehe dort im Log "TAN-Medienbezeichnungen empfangen: Alle Geräte". Der Callback "NEED_PT_TANMEDIA" wird dabei nichtmal ausgelöst, da nur eine Medienbezeichnung vorhanden und diese bereits bekannt ist.

Ich würde das Issue hier schließen. Die weitere Diskussion ist in https://github.com/hbci4j/hbci4java/pull/67 aus meiner Sicht passender aufgehoben.

**Comment by guyyst** [comment]
Ich habe zum Debuggen noch mal das Demo Projekt aufgesetzt und gemerkt, dass das Problem nur auftritt, wenn noch keine Passport Datei vorliegt. Also beim ersten ausführen der Demo hab ich den selben Fehler, beim 2. mal (wenn die `testpassport.dat` geladen werden kann) klappt alles.

In dem Zug ist mir auch aufgefallen, dass es ja eine `HBCIPassportPinTanMemory` Klasse gibt, welche für meine Zwecke eh viel praktischer ist (Bisher hab ich die Passports immer manuell gelöscht. Hätte auf die Idee kommen sollen, dass es eine in-memory Klasse geben könnte...). Durch die Nutzung von `HBCIPassportPinTanMemory` ist das Problem auch gelöst.

Warum das ganze bei der ersten execution mit `HBCIPassportPinTan` nicht klappt verstehe ich natürlich trotzdem nicht, aber Dank der `InMemory` Variante werd' ich das auch nicht weiter debuggen.

**Comment by willuhn** [comment]
Danke für die Rückmeldung.

**Comment by rlill** [comment]
Nach fast einem Jahr scheint die Situation bei der Sparkasse unverändert zu sein. Für die erste Anmeldung + Freigabe muss NEED_PT_TANMETA den Wert "Alle Geräte" zurückgeben, dann klappts. Danke @guyyst !
Der Alias meines Handys hat nicht funktioniert.
