### ISSUE TITLE
PushTan beim registerUser (fetchUPD) benötigt. Wie registriere ich mein Vertrauenswürdiges Gerät?

### ISSUE THREAD

**Issue by ahachmann** [hbci4j/hbci4java#93]
Hallo,
ich habe seit einigen Tagen (10.05.2024) das Problem, dass die Sparkasse bei jedem Verbindungsaufbau eine PushTan von mir haben möchte. Ich gehe davon aus, dass dies daran liegt dass ich das Gerät noch nicht als vertrauenswürdig freigegeben habe.

Wie ist dieser Mechanismus in hbci4java umgesetzt? Wo werden die Properties, die darauf hinweisen, dass das Gerät / Programm schonmal als vertraut freigegeben wurde gespeichert? Wird dies über den Passport gesichert, und wenn ja in welchem Property?

Danke und viele Grüße,

Alexander

**Comment by willuhn** [comment]
Über die Synchronisierungsfunktion des HBCIHandlers:

https://github.com/hbci4j/hbci4java/blob/master/src/main/java/org/kapott/hbci/manager/IHandlerData.java#L44

PS: Die Issues hier sind eigentlich nicht als Support-Plattform gedacht. Dafür gibt es unter https://groups.google.com/forum/?hl=de#!forum/hbci4java eine Mailingliste. Siehe https://github.com/hbci4j/hbci4java
